### ISSUE TITLE
Поддержка Accelerate фреймворка

### ISSUE THREAD

**Issue by netherpyro** [readdle/swift-android-toolchain#15]
Добрый день! 
Спасибо за прекрасный тулчейн

Есть потребность в портировании iOS проекта на Android, но не хватает Accelerate фреймворка в данном тулчейне.
1. Насколько трудо- и времязатратно будет добавить его?
2. Если не получится сделать это настолько быстро насколько возможно, то не могли бы вы предоставить инструкцию как добавить фреймворк в тулчейн?

**Comment by zayass** [comment]
Если вы про это https://developer.apple.com/documentation/accelerate то звучит малореалестично
Проще поискать альтернативу на C и обернуть вокруг нее Swift адаптер с похожим интерфейсом
