### ISSUE TITLE
any chance you can upgrade this to 5.1-5.3 etc?   Trying to use AWS SDK on droid

### ISSUE THREAD

**Issue by johnburkey** [readdle/swift-android-toolchain#16]

**Comment by johnburkey** [comment]
/aws-sdk-swift/.build/checkouts/aws-sdk-swift-core: error: package at '/Users/johnburkey/Projects/buildAndroid/aws-sdk-swift/.build/checkouts/aws-sdk-swift-core' is using Swift tools version 5.1.0 but the installed version is 5.0.0

**Comment by zayass** [comment]
Maybe we will update after 5.3 release
You can try this https://github.com/compnerd/swift-build

**Comment by MihaelIsaev** [comment]
Any chance to get 5.2? 5.3 may be released not very soon...

**Comment by MihaelIsaev** [comment]
I found that android toolchain which is Swift 5.2 and it works great
https://github.com/flowkey/swift-android-toolchain/tree/39847709123f88d577389392711171a1346b6701
but only one problem is that there `PackageDescription` module is missing for some reason https://github.com/flowkey/swift-android-toolchain/issues/11 If you guys could help with that I'd appreciate

**Comment by dstoker-cricut** [comment]
Any news on this? Swift 5.3 has been released and we'd love to get this going on Android!

**Comment by andriydruk** [comment]
Hi, today we released Swift Android Toolchain 5.4. Please check the updated README documentations
https://github.com/readdle/swift-android-toolchain/releases/tag/5.4-r1.
