### ISSUE TITLE
Is it possible to build in 32bit?

### ISSUE THREAD

**Issue by MihaelIsaev** [readdle/swift-android-toolchain#17]
Hey guys, I've just tried to build https://github.com/MillerTechnologyPeru/BluetoothExplorer project using your toolchain and its command `swift-build` and it works fine, compiled the project into `project.so` file, but then I'm getting this runtime error after installation on my device
```java
2020-08-31 09:54:26.310 16443-16443/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.millertech.bluetoothexplorer, PID: 16443
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.millertech.bluetoothexplorer-BxMNxT1OXR67UmbCx_l7pA==/lib/arm/libBluetoothExplorer.so" is 64-bit instead of 32-bit
```
and it seems that it is compiled not for `Android.sdk-armeabi-v7a`

Any suggestion how to build for `Android.sdk-armeabi-v7a`? 🙂 Please 🙏

**Comment by zayass** [comment]
You can build using `swift-build` with `SWIFT_ANDROID_ARCH` environment variable. For example `SWIFT_ANDROID_ARCH=armv7 swift-build`.

But an easier way is using our gradle plugin https://github.com/readdle/swift-android-gradle
See an example here https://github.com/readdle/swift-android-architecture
