### ISSUE TITLE
Android 11 crash A/SwiftRuntime: Fatal error: No foreign strings on Linux in this version of Swift: file /home/vagrant/swift-source/swift/stdlib/public/core/UnicodeHelpers.swift, line 298 A/libc: Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)

### ISSUE THREAD

**Issue by elkasvirElka** [readdle/swift-android-toolchain#18]
Hello,

I am using 'com.readdle.android.swift:gradle:1.4.0' library. Everything was working on Android 29 and lower. 
I got an issue with real device Android 11(Pixel 4a), when I am trying to launch the app it shows the following issue
![image](https://user-images.githubusercontent.com/37272004/103813192-4a919900-5025-11eb-82d7-10a99bcf4599.png)

One thing that I found that it's not crashing if the application in the same project with library(that using a swift file),
but if I call it from another project it crashes.
Unfortunately, I can not put a library in the same project as an application. 

In the project where I have this crash, I don't have any dependencies to 'readdle', 'swift', etc. Only at my library, using readdle lib.

Thank you in advance.

**Comment by andriydruk** [comment]
Hi
There is a new feature in Android 11 [Tagged Pointers](https://source.android.com/devices/tech/debug/tagged-pointers) that lead to a crash with Swift 5. We currently investigate this issue
As I know it is enabled by default only if you set the target SDK to 30 and above
Also you can disable it with [allowNativeHeapPointerTagging](https://developer.android.com/about/versions/11/behavior-changes-11#heap-pointer-tagging)

**Comment by elkasvirElka** [comment]
@andriydruk Thanks android:allowNativeHeapPointerTagging="false" in Manifest works for us.

**Comment by andriydruk** [comment]
Finally, we update our toolchain to Swift 5.7 and disabling allowNativeHeapPointerTagging not needed anymore
