### ISSUE TITLE
Xcode 9.4 support

### ISSUE THREAD

**Issue by rex-remind101** [readdle/swift-android-toolchain#2]
When will Xcode 9.4 support be available? Is Xcode 10 support planned as well?

**Comment by rex-remind101** [comment]
Is this implementation causing compiler errors on Android?

**Comment by zayass** [comment]
No. But we don't see valuable advantages to spend time for supporting 4.1.
If you really need 4.1 you can try this https://github.com/SwiftJava/android_toolchain.
This repo actually based on SwiftJava's toolchain.

**Comment by rex-remind101** [comment]
Cool, I plan on doing some cross platform dev and this requires keeping up with the latest Xcode (latest simulator). I'll see if I can come up with support based on all of your work, thanks!
