### ISSUE TITLE
Xcode 10 support, milestones, wiki, readme.

### ISSUE THREAD

**Issue by talanov** [readdle/swift-android-toolchain#3]
Hi! 

Is Xcode 10 support planned in near future? As I can see @ #2, you were planning it, but I'm curious about current status of project.

Also, README is a little bit off (it links to 4.0b instead of 4.0k), so maybe 4.0k supports not only 9.2?
Couldn't find any active wiki to be maintained, neither milestones list.

Thank you very much for your project, we're actively using it.

**Comment by zayass** [comment]
Hi, @talanov yes README little bit outdated. 4.0k Is steel 4.0 so no Xcode 10 not supported directly.
But you can use it with Xcode 10 and Apple swift 4.0.3 [toolchain](https://swift.org/builds/swift-4.0.3-release/xcode/swift-4.0.3-RELEASE/swift-4.0.3-RELEASE-osx.pkg) from.
With one detail env variable `TOOLCHAINS` should be set in terminal session where you build android

```
export TOOLCHAINS=swift
```
Actually custom toolchain in Xcode is only one way which 4.0k support


We will update README soon.
4.2 is planned but dont I know how near it is

**Comment by andriydruk** [comment]
Documentation was updated: README, ROADMAP and DIFF
