### ISSUE TITLE
Building process question

### ISSUE THREAD

**Issue by NikolayJuly** [readdle/swift-android-toolchain#40]
I tried to follow your building steps on my mac and it looks like scripts are not working. I want understand build process and why it is missing from swift main repo
So I have few questions
1. [Here](https://github.com/readdle/swift-android-toolchain/blob/master/build/macOS/020-build-swift.sh) you do not pass `--android` which make me believe that it will attempt to build macos without android. And as far as I understand you do not even pass ndk path to the build, you only set env variable `ANDROID_NDK_HOME`. Next question here - what about parameters like - `--android-icu-uc`
2. I checked [next step](https://github.com/readdle/swift-android-toolchain/blob/master/build/macOS/040-collect-toolchain-bin.sh) and looks like you copy only results from build swift to bin folder. But if I download prebuild folder I got much more, specifically `toolchain/use/lib` with prebuild libraries, like Dispatch, and I can't find in script, where these files would be copied. 

So It would be great, if you can provide more details, on how to build it locally.
Thanks in advance

**Comment by kostassite** [comment]
Hi,
I am not in the readdle team but I think I can help you with these.

1. The build script for Mac is used only to create swiftpm. The actual android toolchain is built using the files in `build/Linux`, for example [this file](https://github.com/readdle/swift-android-toolchain/blob/master/build/Linux/032-build-swift-arm.sh)  where they use a [preset](https://github.com/readdle/swift-android-toolchain/blob/81e86efea03f449915b4a7308e5f5afd4e8b3004/build/Linux/032-build-swift-arm.sh#L6) which has been added using the [patches](https://github.com/readdle/swift-android-toolchain/tree/master/patches/release/5.4/swift).
2. The files are created and copied by the [Linux scripts](https://github.com/readdle/swift-android-toolchain/tree/master/build/Linux) and they use the [install of the cmake](https://github.com/readdle/swift-android-toolchain/blob/81e86efea03f449915b4a7308e5f5afd4e8b3004/build/Linux/052-build-corelibs.sh#L92-L94) to be generated and copied.

I hope I helped.

**Comment by NikolayJuly** [comment]
Thank you. Now I see action workflow, which explain a lot, my bad, I didn't notice it initially.
Should I close the issue?
