### ISSUE TITLE
Apple silicon support?

### ISSUE THREAD

**Issue by johnburkey** [readdle/swift-android-toolchain#47]
How is m1 support?

**Comment by elkasvirElka** [comment]
@johnburkey Any luck? Looks like my project is broken too. error code 127

**Comment by andriydruk** [comment]
Hi, yes. Swift android toolchain is supported for macOS Apple silicon

Unfortunately macOS Apple silicon Xcode doesn't support custom toolchains 5.4.2. Currently, we recommend installing XCode 13.0 and making it default in Command-Line (I updated documentation in this project).

Toolchain works pretty well on Apple silicon. Most engineers in our team have already migrated to M1 Macbooks. All our internal CI servers work on M1 Mac Minis.
