### ISSUE TITLE
Xcode11 updates

### ISSUE THREAD

**Issue by migueldeicaza** [readdle/swift-android-toolchain#5]
Hello,

I was hoping that the instructions would be updated to Xcode 11, as well as the sample code: https://github.com/readdle/swift-android-architecture

Thanks in advance.

**Comment by zayass** [comment]
Hi @migueldeicaza sorry for so long delay. 
Instructions in this repo should be actual now.
If you have some issues feel free to contact me here or via email to improve docs together.

**Comment by migueldeicaza** [comment]
Thank you Zayass!
