### ISSUE TITLE
What is the current additional size (in KB) of swift runtime per platform?

### ISSUE THREAD

**Issue by allright** [readdle/swift-android-toolchain#7]

**Comment by zayass** [comment]
Size of "minimal" set of libraries for aarch64 compressed as zip around of 25mb
Most of them is icu and Foundation

**Comment by allright** [comment]
So, did you mean that usual size of android app to download will be 25Mb + (App Size without Swift libs) ? 
  For example if my current app size is 5Mb. Size with swift tools will be about 30Mb ?

**Comment by allright** [comment]
I see that Readdle size is 32Mb (on Google Play). It is with swift?

**Comment by zayass** [comment]
Yep. If you worry about the size (in terms of KB) it is definitely not your choice.
