### ISSUE TITLE
Assertion using basic types

### ISSUE THREAD

**Issue by afedor** [readdle/swift-android-toolchain#9]
I have my app working using the toolchain, but the odd thing is I can only call Swift functions that pass or return String.  I can't use Bool/Float/Double/Int etc.  I get an error like:

`W/Swift: Could not find class /Bool - at /Users/fedor/AndroidStudioProjects/RMRGury/app/src/main/swift/.build/checkouts/swift-java-coder/Sources/JNICore+JavaCoder.swift:143
W/Swift: java.lang.ClassNotFoundException: Didn't find class "/Bool" on path: DexPathList[[zip file "/data/app/com.pushovercc.rmrgury-2/base.apk"],nativeLibraryDirectories=[/data/app/com.pushovercc.rmrgury-2/lib/x86, /data/app/com.pushovercc.rmrgury-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
    dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    java.lang.ClassLoader.loadClass(ClassLoader.java:312)
`

I ran the todoapp and that works fine for me, and I copied everything I could think of from that app into mine, but I still can't figure out what the issue is.  Is there something I'm missing?

Thanks

**Comment by andriydruk** [comment]
Looks like you miss `JavaSwift.init()`
This init function should be called after loading the native libraries. 
We have the plan to move all this code to JNI_Load() and initialization will work automatically at loading .so
But, for now, it should be called manually

https://github.com/readdle/swift-android-architecture/blob/todo-swift-mvvm-live/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/Injection.java#L37

**Comment by afedor** [comment]
Yes! That works.  Thanks.  It's a lot simpler than having to pass strings around everywhere :-)

BTW my app is now on Google Play (RMRGury).  It's really just an internal app for our Mountain Rescue Team, but it was _really_ nice not to have to rewrite the back-end code from Swift.
